/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author manas
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double result;
    String op;
    
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton43 = new javax.swing.JButton();
        jtxtresult = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbtnbs = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBtncl = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtndigit7 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jbtndigit8 = new javax.swing.JButton();
        jbtndigit9 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jbtndigit6 = new javax.swing.JButton();
        jbtndigit4 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jbtndigit5 = new javax.swing.JButton();
        jbtnsub = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jbtnmultiply = new javax.swing.JButton();
        jbtndigit1 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jbtndigit2 = new javax.swing.JButton();
        jbtndigit3 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtndigit0 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jbtnstop = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();

        jButton43.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtresult.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jtxtresult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtresultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 50));

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton1.setText("AC");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 74, 70));

        jbtnbs.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnbs.setText("<-");
        jbtnbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton4.setText("CE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 74, 70));

        jBtncl.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jBtncl.setText("C");
        jBtncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclActionPerformed(evt);
            }
        });
        getContentPane().add(jBtncl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 74, 70));

        jButton6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 74, 70));

        jButton7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton8.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 74, 70));

        jButton10.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 74, 70));

        jButton11.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 74, 70));

        jButton12.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton13.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton14.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 74, 70));

        jButton15.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 74, 70));

        jButton16.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 74, 70));

        jButton17.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton18.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 70));

        jButton19.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 74, 70));

        jButton20.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 74, 70));

        jbtnplus.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 74, 60));

        jbtndigit7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit7.setText("7");
        jbtndigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton23.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jbtndigit8.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit8.setText("8");
        jbtndigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 74, 60));

        jbtndigit9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit9.setText("9");
        jbtndigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 74, 60));

        jButton26.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 74, 60));

        jButton27.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton28.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton29.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 74, 60));

        jButton30.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 74, 60));

        jButton31.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 74, 60));

        jButton32.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton33.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton34.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 74, 60));

        jButton35.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 74, 60));

        jButton36.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 74, 60));

        jButton37.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton38.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 74, 60));

        jButton39.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 74, 60));

        jButton40.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 74, 60));

        jbtndigit6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit6.setText("6");
        jbtndigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 74, 70));

        jbtndigit4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit4.setText("4");
        jbtndigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jButton48.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jbtndigit5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit5.setText("5");
        jbtndigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 74, 70));

        jbtnsub.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnsub.setText("-");
        jbtnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 74, 70));

        jButton52.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jButton53.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jButton57.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jButton58.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 74, 70));

        jbtnmultiply.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnmultiply.setText("*");
        jbtnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 74, 60));

        jbtndigit1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit1.setText("1");
        jbtndigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton63.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jbtndigit2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit2.setText("2");
        jbtndigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 74, 60));

        jbtndigit3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit3.setText("3");
        jbtndigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 74, 60));

        jButton66.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 74, 60));

        jButton67.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton68.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton69.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 74, 60));

        jButton70.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 74, 60));

        jButton71.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 74, 60));

        jButton72.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton73.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton74.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 74, 60));

        jButton75.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 74, 60));

        jButton76.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 74, 60));

        jButton77.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton78.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 60));

        jButton79.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 74, 60));

        jButton80.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 74, 60));

        jbtndiv.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 74, 60));

        jbtndigit0.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtndigit0.setText("0");
        jbtndigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton83.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jbtnstop.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnstop.setText(".");
        jbtnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnstopActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 74, 60));

        jbtnequal.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 74, 60));

        jButton86.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 74, 60));

        jButton87.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton88.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton89.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 74, 60));

        jButton90.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 74, 60));

        jButton91.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 74, 60));

        jButton92.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton93.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton94.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 74, 60));

        jButton95.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 74, 60));

        jButton96.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 74, 60));

        jButton97.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton98.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 74, 60));

        jButton99.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 74, 60));

        jButton100.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 74, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void EntereNumber(String q)
 {
     String Nums = jtxtresult.getText() +q;
     jtxtresult.setText(Nums );
 }
    
    private void jtxtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtresultActionPerformed

    private void jbtndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit7ActionPerformed
        // TODO add your handling code here:
        EntereNumber("7");
    }//GEN-LAST:event_jbtndigit7ActionPerformed

    private void jbtndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit8ActionPerformed
        EntereNumber("8");
    }//GEN-LAST:event_jbtndigit8ActionPerformed

    private void jbtndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit9ActionPerformed
        EntereNumber("9");
    }//GEN-LAST:event_jbtndigit9ActionPerformed

    private void jbtndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit4ActionPerformed
        EntereNumber("4");
    }//GEN-LAST:event_jbtndigit4ActionPerformed

    private void jbtndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit5ActionPerformed
        EntereNumber("5");
    }//GEN-LAST:event_jbtndigit5ActionPerformed

    private void jbtndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit6ActionPerformed
        EntereNumber("6");
    }//GEN-LAST:event_jbtndigit6ActionPerformed

    private void jbtndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit1ActionPerformed
        EntereNumber("1");
    }//GEN-LAST:event_jbtndigit1ActionPerformed

    private void jbtndigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit2ActionPerformed
        EntereNumber("2");
    }//GEN-LAST:event_jbtndigit2ActionPerformed

    private void jbtndigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit3ActionPerformed
        EntereNumber("3");
    }//GEN-LAST:event_jbtndigit3ActionPerformed

    private void jbtndigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit0ActionPerformed
        EntereNumber("0");
    }//GEN-LAST:event_jbtndigit0ActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "/"; 
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "*";
    }//GEN-LAST:event_jbtnmultiplyActionPerformed

    private void jbtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubActionPerformed
       NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "-";
    }//GEN-LAST:event_jbtnsubActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "+ ";
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jBtnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclActionPerformed
        jtxtresult.setText("");
    }//GEN-LAST:event_jBtnclActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jtxtresult.setText("");
        
        String Fn,Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
         Fn ="";
         Sn = "";
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbsActionPerformed
        String backsp = null;
        
        if (jtxtresult.getText().length()>0){
            StringBuilder sb = new StringBuilder(jtxtresult.getText());
            sb.deleteCharAt(jtxtresult.getText().length()-1);
            backsp = sb.toString();
            jtxtresult.setText(backsp);
            
        }
    }//GEN-LAST:event_jbtnbsActionPerformed

    private void jbtnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstopActionPerformed
        if (! jtxtresult.getText().contains("."))
        {
            jtxtresult.setText(jtxtresult.getText() + jbtnstop.getText());
        }
    }//GEN-LAST:event_jbtnstopActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
        NumEnter2 = Double.parseDouble(jtxtresult.getText() );
        
        if(op =="+"){
            
            result = NumEnter1 + NumEnter2;
        jtxtresult.setText(String.valueOf(result)); 
        }
        
        else if (op == "-"){
            result = NumEnter1 - NumEnter2;
        jtxtresult.setText(String.valueOf(result)); 
            
        }
        
        else if (op == "*"){
            result = NumEnter1 * NumEnter2;
        jtxtresult.setText(String.valueOf(result)); 
            
        }
         else if (op == "/"){
            result = NumEnter1 / NumEnter2;
        jtxtresult.setText(String.valueOf(result)); 
            
        }
        
        
        
    }//GEN-LAST:event_jbtnequalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtncl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JButton jbtnbs;
    private javax.swing.JButton jbtndigit0;
    private javax.swing.JButton jbtndigit1;
    private javax.swing.JButton jbtndigit2;
    private javax.swing.JButton jbtndigit3;
    private javax.swing.JButton jbtndigit4;
    private javax.swing.JButton jbtndigit5;
    private javax.swing.JButton jbtndigit6;
    private javax.swing.JButton jbtndigit7;
    private javax.swing.JButton jbtndigit8;
    private javax.swing.JButton jbtndigit9;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnmultiply;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnstop;
    private javax.swing.JButton jbtnsub;
    private javax.swing.JTextField jtxtresult;
    // End of variables declaration//GEN-END:variables
}
